name: Deploy to Fly

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    name: Build & Deploy to Fly
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install flyctl
        run: |
          curl -L https://fly.io/install.sh | sh
          echo "::add-path::${HOME}/.fly/bin"

      - name: Authenticate flyctl
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        run: |
          ${HOME}/.fly/bin/flyctl auth login --access-token "$FLY_API_TOKEN"

      - name: Deploy to Fly (remote build)
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        run: |
          ${HOME}/.fly/bin/flyctl deploy --remote-only --config fly.toml --app dsfmlproject
